# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"words2ints": "00_core.ipynb",
         "traceback": "00_core.ipynb",
         "matrix": "00_core.ipynb",
         "smithwaterman": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://dresen.github.io/smithwaterman/"

git_url = "https://github.com/dresen/smithwaterman/tree/master/"

def custom_doc_links(name): return None
